# Generated by Django 5.2.4 on 2025-07-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ImagenNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='noticias/noticias_imagenes')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('noticia_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=85)),
                ('subtitulo', models.CharField(max_length=150)),
                ('contenido', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
