# Generated by Django 5.2.4 on 2025-08-14 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_contactmessage'),
        ('noticias', '0004_delete_mensajecontacto'),
    ]

    operations = [
    ]
