# Generated by Django 5.2.4 on 2025-08-03 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_alter_comentario_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='nombre',
            new_name='usuario',
        ),
    ]
