# Generated by Django 5.2.4 on 2025-08-03 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0003_noticia_remove_comentario_autor_and_more'),
        ('noticias', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='noticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.noticia'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='contenido',
            field=models.TextField(default='Comentario de prueba'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Noticia',
        ),
    ]
