# Generated by Django 5.2.4 on 2025-08-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen_perfil',
            field=models.ImageField(blank=True, default='usuario/user-default.png', null=True, upload_to='usuario'),
        ),
    ]
